name: SwiftLint

on: pull_request

jobs:
  swiftlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: norio-nomura/action-swiftlint@3.2.1
      env:
        DIFF_BASE: ${{ github.base_ref }}
