name: SwiftLint

on: pull_request

jobs:
  swiftlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: pepibumur/action-swiftlint@0d4afd006bb24e4525b5afcefd4ab5e2537193ac
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
